---
- name: Install Docker on Ubuntu
  hosts: all
  remote_user: slave
  become: yes
  tasks:
    - name: Update packages index
      apt:
        update_cache: yes

    - name: Install needed packages to add the docker repo
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add the GPG key of the docker repo
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present

    - name: Add the docker repo
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
        state: present
        filename: docker

    - name: Update the packages index after add the docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Check if the docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if the docker installation is done
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Show the docker version
      debug:
        msg: "Docker is installed, version: {{ docker_version.stdout }}"
